---
- name: Ansible OneView Synergy playbook to deploy Compute Module(s) using a Server Profile Template
  hosts: SLES
  gather_facts: no
  vars:
    - config: "{{ playbook_dir }}/oneview_config.json"
    - server_template: "SLES 12 deployment with Streamer"

  tasks:
    - name: Creating Server Profile [{{ inventory_hostname }}] from Server Profile Template [{{ server_template }}]
      oneview_server_profile:
        config: "{{ config }}"
        data:
          serverProfileTemplateName: "{{ server_template }}"
          name: "{{ inventory_hostname }}"
        auto_assign_server_hardware: True
      # params: # Supported only in API version >= 600
      #   force: True
      # state: present
      delegate_to: localhost
      register: result

    - name: Task result of the Server Profile(s) creation
      debug: 
        msg: "{{ result.msg }}"

    - name: Powering on the Compute Module(s)
      oneview_server_hardware:
        config: "{{ config }}"
        state: power_state_set
        data:
            name : "{{ server_hardware.name }}"
            powerStateData:
                powerState: "On"
                powerControl: "MomentaryPress"
      delegate_to: localhost


    - name: Collecting Compute Module(s) information
      oneview_server_profile_facts:
        config: "{{ config }}"
        name: "{{ inventory_hostname }}"
      delegate_to: localhost

   #- debug: var=server_profiles

    - name: Displaying IP address(s) assigned to the Compute module(s)
      debug: 
        msg: "{{ (server_profiles | map(attribute='osDeploymentSettings.osCustomAttributes') | list )[0] | selectattr('name', 'equalto', 'ManagementNIC.ipaddress') | map(attribute='value') | list }}"

