---
- hosts: localhost
  vars:
    config: "{{ playbook_dir }}/oneview_config.json"
  tasks:
    - name: Gather facts about all Server Hardwares
      oneview_server_hardware_facts:
        config: "{{ config }}"
      delegate_to: localhost
    - debug:
        var: hostvars[inventory_hostname]
